# Generated by Django 5.0 on 2023-12-19 16:29

import django.core.validators
import django.db.models.deletion
import recipes_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('level', models.CharField(db_column='level', max_length=10, validators=[recipes_app.validators.validate_level])),
                ('ingredients', models.CharField(db_column='ingredients', max_length=500)),
                ('instructions', models.CharField(db_column='instructions', max_length=500)),
                ('delete', models.BooleanField(db_column='delete', default=False)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_number', models.SmallIntegerField(db_column='rating_number', validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator])),
                ('rating_date', models.DateField(auto_now_add=True, db_column='rating_date')),
                ('recipe', models.ForeignKey(db_column='recipe', on_delete=django.db.models.deletion.RESTRICT, to='recipes_app.recipe')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
